// timer file for spawn points on map 1800 for Elves

IF	GlobalGT("ZyELReserveSquads","GLOBAL",0)
	Global("MyOwnTimerSet","LOCALS",1)
THEN
	RESPONSE #100
	SetGlobal("MyOwnTimerSet","LOCALS",0)
	SetGlobalTimer("MyOwnTimer","LOCALS",100)
END

// when reserves are out

IF	!GlobalGT("ZyELReserveSquads","GLOBAL",0)	
	Global("MyOwnTimerSet","LOCALS",1)
THEN
	RESPONSE #100
	SetGlobal("MyOwnTimerSet","LOCALS",0)
	SetGlobalTimer("MyOwnTimer","LOCALS",200)
END